"""Write the API contract -- the OpenAPI document and the TypeScript types.

```text
python scripts/task.py openapi          regenerate both files
python scripts/task.py openapi-check    fail if either is stale
```

The committed files are the web/API contract, and the check is what stops the
two halves of the repo disagreeing quietly. A generated file that is not diffed
in CI is wrong within a fortnight -- the endpoint changes, the client keeps its
old types, and the mismatch surfaces as an `undefined` in somebody's browser
rather than as a red build.

The TypeScript is generated from the same document rather than written beside
it, for the reason every generated thing in this repo exists: a hand-kept
mirror is a second source of truth that nobody notices going stale. It covers
the schema shapes this API actually uses -- objects, arrays, enums, nullable
unions, and `int | string` for the money-or-ratio fields -- and refuses
anything it does not recognise rather than emitting `any`, because `any` is how
a contract stops being one.

Serialised with sorted keys and a trailing newline so a diff is about the API
and never about dictionary ordering.
"""

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "api" / "src"))

SHARED = ROOT / "packages" / "shared-types"
DOCUMENT = SHARED / "openapi.json"
TYPES = SHARED / "api.ts"

BANNER = (
    "// Generated by scripts/export_openapi.py. Do not edit; `task.py openapi-check` gates it.\n"
)


class UnrenderableSchemaError(TypeError):
    """A schema shape the generator does not handle. Better than emitting `any`."""


def document() -> dict[str, Any]:
    from main import create_app

    schema: dict[str, Any] = create_app().openapi()
    return schema


def rendered_json(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# --------------------------------------------------------------------------
# TypeScript
# --------------------------------------------------------------------------


def rendered_types(schema: dict[str, Any]) -> str:
    components: dict[str, Any] = schema.get("components", {}).get("schemas", {})
    blocks = [BANNER, "\n"]
    for name in sorted(components):
        blocks.append(_interface(name, components[name]))
    blocks.append(_paths(schema))
    return "".join(blocks)


def _interface(name: str, definition: dict[str, Any]) -> str:
    if definition.get("enum"):
        members = " | ".join(json.dumps(value) for value in definition["enum"])
        return f"export type {name} = {members};\n\n"

    properties: dict[str, Any] = definition.get("properties", {})
    required = set(definition.get("required", []))
    lines = [f"export interface {name} {{"]
    for field in properties:
        optional = "" if field in required else "?"
        lines.append(f"  {_key(field)}{optional}: {_type(properties[field])};")
    lines.append("}\n\n")
    return "\n".join(lines)


def _key(field: str) -> str:
    return field if field.isidentifier() else json.dumps(field)


def _type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return str(node["$ref"]).removeprefix("#/components/schemas/")
    if "anyOf" in node:
        return " | ".join(dict.fromkeys(_type(option) for option in node["anyOf"]))
    if "allOf" in node and len(node["allOf"]) == 1:
        return _type(node["allOf"][0])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    if "const" in node:
        return json.dumps(node["const"])

    kind = node.get("type")
    if kind == "array":
        item = _type(node.get("items", {}))
        # A union has to be parenthesised before the suffix, or
        # `string | number[]` reads as "a string, or an array of numbers".
        return f"({item})[]" if " | " in item else f"{item}[]"
    if kind == "object":
        extra = node.get("additionalProperties")
        inner = _type(extra) if isinstance(extra, dict) else "unknown"
        return f"Record<string, {inner}>"
    scalar = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(str(kind))
    if scalar is not None:
        return scalar
    if not node:
        # An unconstrained field -- `dict[str, Any]` on an error detail. It is
        # genuinely unknown, and `unknown` says so where `any` would not.
        return "unknown"
    raise UnrenderableSchemaError(f"no TypeScript for schema {node!r}")


def _paths(schema: dict[str, Any]) -> str:
    """The route table, as literal types. What a client may call, and nothing else."""
    routes = sorted(schema.get("paths", {}))
    members = "\n".join(f"  | {json.dumps(path)}" for path in routes)
    return f"export type ApiPath =\n{members};\n"


# --------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    checking = "--check" in argv
    schema = document()
    wanted = {DOCUMENT: rendered_json(schema), TYPES: rendered_types(schema)}

    if not checking:
        SHARED.mkdir(parents=True, exist_ok=True)
        for path, text in wanted.items():
            path.write_text(text, encoding="utf-8", newline="\n")
        print(
            f"openapi written: {len(schema['paths'])} paths, "
            f"{len(schema.get('components', {}).get('schemas', {}))} schemas"
        )
        return 0

    for path, text in wanted.items():
        relative = path.relative_to(ROOT).as_posix()
        if not path.exists():
            print(f"{relative} does not exist; run `task.py openapi`", file=sys.stderr)
            return 1
        if path.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print(
                f"{relative} is stale -- the API changed and the contract did not.\n"
                "Run `python scripts/task.py openapi` and commit the result.",
                file=sys.stderr,
            )
            return 1
    print("openapi OK (committed contract matches the app)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
